.TH motor 1 "December 30, 2017" "" "eltools"

.SH НАЗВАНИЕ
motor \- программа для расчёта тока электродвигателя

.SH СИНТАКСИС
.br
.B 380 [-dhv] | material(al|cu) cross_section cos length amperage
.br

.SH ОПИСАНИЕ
.RS 4
Список параметров
.RE
.RS 4
-h или --help вывод справки
.RE
.RS 4
-v или --version вывод версии
.RE
.RS 4
-m - режим. ac - переменный ток, dc - постоянный ток
.RE
.RS 4
-u - напряжение, кВ
.RE
.RS 4
-p - мощность, кВт
.RE
.RS 4
-c - коэффициент мощности
.RE
.RS 4
-n - КПД
.RE

.SH КОД ВЫХОДА
0 в случае успешного завершения и -1 в случае ошибки


.SH СМОТРИТЕ ТАКЖЕ
scc(1), vl380(1), om(1)

