.TH vl380 1 "December 30, 2017" "" "eltools"

.SH НАЗВАНИЕ
vl380 \- программа для расчётов падений напряжений в трёхфазных кабельных сетях напряжением 0.4 кВ

.SH СИНТАКСИС
.br
.B vl380 [-dhv]  material(al|cu) cross_section cos length amperage
.br

.SH ОПИСАНИЕ
.RS 4
Список параметров
.RE
.RS 4
-h вывод справки
.RE
.RS 4
-v вывод версии
.RE
.RS 4
-d - диалоговый режим
.RE
.RS 4
material - материал (al или cu)
.RE
.RS 4
cross_section - сечение жилы, мм2
.RE
.RS 4
cos - коэффициент мощности
.RE
.RS 4
length - длина, км
.RE
.RS 4
amperage - сила тока, А
.RE

.SH КОД ВЫХОДА
0 в случае успешного завершения и -1 в случае ошибки

.SH ОШИБКИ
Отсутствует интернационализация.

.SH СМОТРИТЕ ТАКЖЕ
scc(1), motor(1), om(1)

